query EpisodeById($id: Float!) {
	allEpisode(where: { episodeNumber: { eq: $id } }) {
		question
        answer
        answerLink
        spotifyUrl
		episodeNumber
        solvedBy {
			_id
			name
		}
	}
}
