query EpisodeById($id: Float!) {
	allEpisode(where: { number: { eq: $id } }) {
		spotifyUrl
		number
		title
		questions {
			question
			answer
			answerLink
			solvedBy {
				_id
				name
			}
		}
	}
}
